<table class="column_95 textMid tablesorter" id="roleListTable">
    <caption>内存详细信息</caption>
    <tr>
        <td class="column_55">总内存</td>
        <td><{$meminfo.MemTotal}></td>
    </tr>
    <tr>
        <td>空闲内存</td>
        <td><{$meminfo.MemFree}></td>
    </tr>
    <tr>
        <td>共享内存</td>
        <td><{$meminfo.Cached}></td>
    </tr>
    <tr>
        <td>buffers内存</td>
        <td><{$meminfo.Buffers}></td>
    </tr>
    <tr>
        <td>缓冲内存</td>
        <td><{$meminfo.SwapCached}></td>
    </tr>
    <tr>
        <td>总交换内存</td>
        <td><{$meminfo.DirectMap4k}></td>
    </tr>
    <tr>
        <td>空闲交换内存</td>
        <td><{$meminfo.DirectMap4M}></td>
    </tr>
</table>
