<?php
	$menuArr=array(array('name'=>'系统管理',
				  		'cfgname'=>'systemManagement',
				   		'subMenu'=>array(array(
												 'name'=>'系统概览',
												 'cfgname'=>'overview',
												 'subMenu'=>array()
												 ),
										array(
											  	'name'=>'快捷配置',
												'cfgname'=>'quick',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'配置',
												'cfgname'=>'conf',
												'subMenu'=>array(array(
																		'name'=>'日期时间',
																		'cfgname'=>'date',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'系统参数',
																		'cfgname'=>'argument',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'集中管理',
																		'cfgname'=>'central',
																		'subMenu'=>array()
																	  )
																)
											  ),
										array(
											  	'name'=>'管理员设置',
												'cfgname'=>'admin',
												'subMenu'=>array(array(
																		'name'=>'管理员帐号',
																		'cfgname'=>'account',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'管理主机',
																		'cfgname'=>'host',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'管理证书',
																		'cfgname'=>'cert',
																		'subMenu'=>array()
																	  ),
																  array(
																		'name'=>'管理方式',
																		'cfgname'=>'way',
																		'subMenu'=>array()
																	  )
																 )
											  ),
										array(
											  	'name'=>'维护',
												'cfgname'=>'maintain',
												'subMenu'=>array(array(
																		'name'=>'模块升级',
																		'cfgname'=>'upgrade',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'备份与恢复',
																		'cfgname'=>'backrenew',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'模块许可',
																		'cfgname'=>'permit',
																		'subMenu'=>array()
																	  ),
																  array(
																		'name'=>'批处理工具',
																		'cfgname'=>'batching',
																		'subMenu'=>array()
																	  )
																 )
											  )
										   )
					   ),
			 array('name'=>'网络管理',
				  		'cfgname'=>'networkManagement',
				   		'subMenu'=>array(array(
												 'name'=>'网络接口',
												 'cfgname'=>'interface',
												 'subMenu'=>array(array(
																		'name'=>'物理设备',
																		'cfgname'=>'physics',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'别名设备',
																		'cfgname'=>'alias',
																		'subMenu'=>array()
																	  )
																  )
												 ),
										array(
											  	'name'=>'基本配置',
												'cfgname'=>'basic',
												'subMenu'=>array(array(
																		'name'=>'域名服务器',
																		'cfgname'=>'realm',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'静态路由',
																		'cfgname'=>'route',
																		'subMenu'=>array()
																	  ))
											  ),
										array(
											  	'name'=>'高可用性',
												'cfgname'=>'HA',
												'subMenu'=>array(array(
																		'name'=>'双击热备',
																		'cfgname'=>'hotspare',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'负载均衡',
																		'cfgname'=>'balanced',
																		'subMenu'=>array()
																	  ))
											  )
										   )
					   ),
			 array('name'=>'资源配置',
				  		'cfgname'=>'resConf',
				   		'subMenu'=>array(array(
												 'name'=>'地址',
												 'cfgname'=>'addr',
												 'subMenu'=>array()
												 ),
										array(
											  	'name'=>'时间',
												'cfgname'=>'time',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'用户',
												'cfgname'=>'user',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'地址绑定',
												'cfgname'=>'addrBind',
												'subMenu'=>array()
											  )
										   )
					   ),
			  array('name'=>'客户端',
				  		'cfgname'=>'client',
				   		'subMenu'=>array(array(
												 'name'=>'文件交换',
												 'cfgname'=>'fileEx',
												 'subMenu'=>array()
												 ),
										array(
											  	'name'=>'数据库同步',
												'cfgname'=>'dbSync',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'安全浏览',
												'cfgname'=>'safeBrowse',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'FTP访问',
												'cfgname'=>'ftp',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'邮件访问',
												'cfgname'=>'mail',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'数据库访问',
												'cfgname'=>'db',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'定制访问',
												'cfgname'=>'customized',
												'subMenu'=>array(array(
																		'name'=>'TCP访问',
																		'cfgname'=>'tcpvisit',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'UDP访问',
																		'cfgname'=>'udpvisit',
																		'subMenu'=>array()
																	  ))
											  ),
										array(
											  	'name'=>'安全通道',
												'cfgname'=>'safePass',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'消息传输',
												'cfgname'=>'msgTrans',
												'subMenu'=>array()
											  )
										   )
					   ),
			  array('name'=>'服务端',
				  		'cfgname'=>'server',
				   		'subMenu'=>array(array(
												 'name'=>'文件交换',
												 'cfgname'=>'fileEx',
												 'subMenu'=>array()
												 ),
										array(
											  	'name'=>'数据库同步',
												'cfgname'=>'dbSync',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'安全浏览',
												'cfgname'=>'safeBrowse',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'FTP访问',
												'cfgname'=>'ftp',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'邮件访问',
												'cfgname'=>'mail',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'数据库访问',
												'cfgname'=>'db',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'定制访问',
												'cfgname'=>'customized',
												'subMenu'=>array(array(
																		'name'=>'TCP访问',
																		'cfgname'=>'tcpvisit',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'UDP访问',
																		'cfgname'=>'udpvisit',
																		'subMenu'=>array()
																	  ))
											  ),
										array(
											  	'name'=>'安全通道',
												'cfgname'=>'safePass',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'消息传输',
												'cfgname'=>'msgTrans',
												'subMenu'=>array()
											  )
										   )
					   ),
			   array('name'=>'应用防护',
				  		'cfgname'=>'appS',
				   		'subMenu'=>array(array(
												 'name'=>'病毒防护',
												 'cfgname'=>'virusProtection',
												 'subMenu'=>array()
												 ),
										array(
											  	'name'=>'入侵防护',
												'cfgname'=>'ips',
												'subMenu'=>array(array(
																		'name'=>'基本配置',
																		'cfgname'=>'basic',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'策略配置',
																		'cfgname'=>'strategy',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'自定义检测',
																		'cfgname'=>'custom',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'扫描检测配置',
																		'cfgname'=>'scan',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'自动响应配置',
																		'cfgname'=>'respond',
																		'subMenu'=>array()
																	  ),
																 array(
																		'name'=>'检测结果',
																		'cfgname'=>'detection',
																		'subMenu'=>array()
																	  ))
											  )
										   )
					   ),
			   array('name'=>'状态监控',
				  		'cfgname'=>'statMonitor',
				   		'subMenu'=>array(array(
												 'name'=>'资源状态',
												 'cfgname'=>'res',
												 'subMenu'=>array()
												 ),
										array(
											  	'name'=>'网络状态',
												'cfgname'=>'network',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'用户状态',
												'cfgname'=>'user',
												'subMenu'=>array()
											  ),
										array(
											  	'name'=>'网络测试',
												'cfgname'=>'test',
												'subMenu'=>array()
											  )
										   )
					   ),
			    array('name'=>'日志与报表',
				  		'cfgname'=>'log',
				   		'subMenu'=>array(array(
												 'name'=>'日志配置',
												 'cfgname'=>'conf',
												 'subMenu'=>array()
												 ),
										array(
											  	'name'=>'日志访问',
												'cfgname'=>'view',
												'subMenu'=>array()
											  )
										   )
					   )
				 );
?>